language:
- objective-c
env:
  global:
  - LATEST_TAG=1
  matrix:
  - VERSION=2.7.8
  - VERSION=3.3.5
  - VERSION=3.4.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate
  - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag tornado; fi
  - cd tornado
  - python setup.py bdist_wheel
  - delocate-wheel dist/*.whl
  - rename_wheels dist
  - pip install dist/*.whl
  - cd ..
script:
  - pip install futures mock pycares pycurl
  - if [ `get_py_digit` == 2 ]; then pip install twisted; fi
  - mkdir tmp_for_test
  - cd tmp_for_test
  - python -m tornado.test.runtests
  - cd ..
before_deploy: cd tornado/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "JxJFpYAsFzpXznFLHGvB0JTgTlv7K4kzllJuZqboOIMaVWXuvYW/SvxNoMp+guPcgovCNQmLMeYJsbnYAHvFu+cBYrIIYl6mS6zHUSBmvC/VPtSrCmB758bJv7tTIH+aLWm79xrrV7rgEOxOcGuQnhM3ukhKJoDWSSHhBbHlJ+E="
  region: ORD
  container: wheels
